// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlxxcukgqaehsbbncvwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseHhjdWtncWFlaHNiYm5jdnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2ODAzMTMsImV4cCI6MjA1MTI1NjMxM30.vhfZPVuSXxuvTWg-zNYNjvfJgbMSgAOeBF1MoAEA7KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);